### ISSUE TITLE
Commits are not working

### ISSUE THREAD

**Issue by EmreAtes** [CCI-MOC/more#25]
Even though the commits are not commented out in local.conf, the pulled repos have different commits. I think this might also be the reason for #24.

**Comment by HuzefaMandvi** [comment]
The commits only work before the first run of `stack.sh`, did you happen to try using them after that?

Also, I realize now that you specified a commit for tempest in local.conf but I haven't added commit support for tempest - I can do that today.

**Comment by EmreAtes** [comment]
I'm trying out a fresh install, I'll let you know how it turns out

**Comment by EmreAtes** [comment]
I just started a fresh ORE, and neutron is on commit 259078ad325ea7458ac734cc22835ad5dc865ce2 instead of b0ca86f6b27069c6cc5726c950008c636aa9aad9 in local.conf

**Comment by HuzefaMandvi** [comment]
I think I've found a fix. I'll boot a fresh VM to make sure...

**Comment by HuzefaMandvi** [comment]
So here's what was happening:

To add commit support, I edited the devstack/lib/$SERVICE files to reset to the given commit immediately after cloning a repo, see: https://github.com/CCI-MOC/ORE/blob/master/patch/lib/cinder#L445

However, in neutron for some reason there is a legacy install as well as the standard (updated, i guess) install. https://github.com/CCI-MOC/ORE/blob/master/patch/lib/neutron#L552

For whatever reason, the legacy install `install_mutnauq` is called instead of `install_neutron_new`. I had patched the install_neutron_new function but not the legacy mutnauq one.
